// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/modelcontextprotocol/go-sdk/auth (interfaces: OAuthHandler)
//
// Generated by this command:
//
//	mockgen -destination=internal/agent/tools/mcp/mock_oauthhandler_test.go -package=mcp github.com/modelcontextprotocol/go-sdk/auth OAuthHandler
//

// Package mcp is a generated GoMock package.
package mcp

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	oauth2 "golang.org/x/oauth2"
)

// MockOAuthHandler is a mock of OAuthHandler interface.
type MockOAuthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthHandlerMockRecorder
	isgomock struct{}
}

// MockOAuthHandlerMockRecorder is the mock recorder for MockOAuthHandler.
type MockOAuthHandlerMockRecorder struct {
	mock *MockOAuthHandler
}

// NewMockOAuthHandler creates a new mock instance.
func NewMockOAuthHandler(ctrl *gomock.Controller) *MockOAuthHandler {
	mock := &MockOAuthHandler{ctrl: ctrl}
	mock.recorder = &MockOAuthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthHandler) EXPECT() *MockOAuthHandlerMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockOAuthHandler) Authorize(arg0 context.Context, arg1 *http.Request, arg2 *http.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authorize indicates an expected call of Authorize.
func (mr *MockOAuthHandlerMockRecorder) Authorize(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockOAuthHandler)(nil).Authorize), arg0, arg1, arg2)
}

// TokenSource mocks base method.
func (m *MockOAuthHandler) TokenSource(arg0 context.Context) (oauth2.TokenSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenSource", arg0)
	ret0, _ := ret[0].(oauth2.TokenSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenSource indicates an expected call of TokenSource.
func (mr *MockOAuthHandlerMockRecorder) TokenSource(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenSource", reflect.TypeOf((*MockOAuthHandler)(nil).TokenSource), arg0)
}
