// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/workspace (interfaces: Workspace)
//
// Generated by this command:
//
//	mockgen -destination=internal/ui/model/mock_workspace_test.go -package=model github.com/NaturalSelect/angela/internal/workspace Workspace
//

// Package model is a generated GoMock package.
package model

import (
	context "context"
	reflect "reflect"
	time "time"

	tea "charm.land/bubbletea/v2"
	catwalk "charm.land/catwalk/pkg/catwalk"
	mcp "github.com/NaturalSelect/angela/internal/agent/tools/mcp"
	commands "github.com/NaturalSelect/angela/internal/commands"
	config "github.com/NaturalSelect/angela/internal/config"
	history "github.com/NaturalSelect/angela/internal/history"
	lsp "github.com/NaturalSelect/angela/internal/lsp"
	message "github.com/NaturalSelect/angela/internal/message"
	oauth "github.com/NaturalSelect/angela/internal/oauth"
	permission "github.com/NaturalSelect/angela/internal/permission"
	proto "github.com/NaturalSelect/angela/internal/proto"
	question "github.com/NaturalSelect/angela/internal/question"
	session "github.com/NaturalSelect/angela/internal/session"
	skills "github.com/NaturalSelect/angela/internal/skills"
	undo "github.com/NaturalSelect/angela/internal/undo"
	workspace "github.com/NaturalSelect/angela/internal/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspace is a mock of Workspace interface.
type MockWorkspace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMockRecorder
	isgomock struct{}
}

// MockWorkspaceMockRecorder is the mock recorder for MockWorkspace.
type MockWorkspaceMockRecorder struct {
	mock *MockWorkspace
}

// NewMockWorkspace creates a new mock instance.
func NewMockWorkspace(ctrl *gomock.Controller) *MockWorkspace {
	mock := &MockWorkspace{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspace) EXPECT() *MockWorkspaceMockRecorder {
	return m.recorder
}

// AgentAbandonBranch mocks base method.
func (m *MockWorkspace) AgentAbandonBranch(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AgentAbandonBranch", sessionID)
}

// AgentAbandonBranch indicates an expected call of AgentAbandonBranch.
func (mr *MockWorkspaceMockRecorder) AgentAbandonBranch(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentAbandonBranch", reflect.TypeOf((*MockWorkspace)(nil).AgentAbandonBranch), sessionID)
}

// AgentActive mocks base method.
func (m *MockWorkspace) AgentActive(ctx context.Context, sessionID string) (workspace.ActiveAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentActive", ctx, sessionID)
	ret0, _ := ret[0].(workspace.ActiveAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentActive indicates an expected call of AgentActive.
func (mr *MockWorkspaceMockRecorder) AgentActive(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentActive", reflect.TypeOf((*MockWorkspace)(nil).AgentActive), ctx, sessionID)
}

// AgentCancel mocks base method.
func (m *MockWorkspace) AgentCancel(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AgentCancel", sessionID)
}

// AgentCancel indicates an expected call of AgentCancel.
func (mr *MockWorkspaceMockRecorder) AgentCancel(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentCancel", reflect.TypeOf((*MockWorkspace)(nil).AgentCancel), sessionID)
}

// AgentClearQueue mocks base method.
func (m *MockWorkspace) AgentClearQueue(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AgentClearQueue", sessionID)
}

// AgentClearQueue indicates an expected call of AgentClearQueue.
func (mr *MockWorkspaceMockRecorder) AgentClearQueue(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentClearQueue", reflect.TypeOf((*MockWorkspace)(nil).AgentClearQueue), sessionID)
}

// AgentEditActive mocks base method.
func (m *MockWorkspace) AgentEditActive(ctx context.Context, sessionID string, edit config.ActiveAgentEdit) (workspace.ActiveAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentEditActive", ctx, sessionID, edit)
	ret0, _ := ret[0].(workspace.ActiveAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentEditActive indicates an expected call of AgentEditActive.
func (mr *MockWorkspaceMockRecorder) AgentEditActive(ctx, sessionID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentEditActive", reflect.TypeOf((*MockWorkspace)(nil).AgentEditActive), ctx, sessionID, edit)
}

// AgentIsBusy mocks base method.
func (m *MockWorkspace) AgentIsBusy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentIsBusy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AgentIsBusy indicates an expected call of AgentIsBusy.
func (mr *MockWorkspaceMockRecorder) AgentIsBusy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentIsBusy", reflect.TypeOf((*MockWorkspace)(nil).AgentIsBusy))
}

// AgentIsReady mocks base method.
func (m *MockWorkspace) AgentIsReady() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentIsReady")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AgentIsReady indicates an expected call of AgentIsReady.
func (mr *MockWorkspaceMockRecorder) AgentIsReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentIsReady", reflect.TypeOf((*MockWorkspace)(nil).AgentIsReady))
}

// AgentIsSessionBranch mocks base method.
func (m *MockWorkspace) AgentIsSessionBranch(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentIsSessionBranch", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AgentIsSessionBranch indicates an expected call of AgentIsSessionBranch.
func (mr *MockWorkspaceMockRecorder) AgentIsSessionBranch(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentIsSessionBranch", reflect.TypeOf((*MockWorkspace)(nil).AgentIsSessionBranch), sessionID)
}

// AgentIsSessionBusy mocks base method.
func (m *MockWorkspace) AgentIsSessionBusy(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentIsSessionBusy", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AgentIsSessionBusy indicates an expected call of AgentIsSessionBusy.
func (mr *MockWorkspaceMockRecorder) AgentIsSessionBusy(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentIsSessionBusy", reflect.TypeOf((*MockWorkspace)(nil).AgentIsSessionBusy), sessionID)
}

// AgentQueuedPrompts mocks base method.
func (m *MockWorkspace) AgentQueuedPrompts(sessionID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentQueuedPrompts", sessionID)
	ret0, _ := ret[0].(int)
	return ret0
}

// AgentQueuedPrompts indicates an expected call of AgentQueuedPrompts.
func (mr *MockWorkspaceMockRecorder) AgentQueuedPrompts(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentQueuedPrompts", reflect.TypeOf((*MockWorkspace)(nil).AgentQueuedPrompts), sessionID)
}

// AgentQueuedPromptsList mocks base method.
func (m *MockWorkspace) AgentQueuedPromptsList(sessionID string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentQueuedPromptsList", sessionID)
	ret0, _ := ret[0].([]string)
	return ret0
}

// AgentQueuedPromptsList indicates an expected call of AgentQueuedPromptsList.
func (mr *MockWorkspaceMockRecorder) AgentQueuedPromptsList(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentQueuedPromptsList", reflect.TypeOf((*MockWorkspace)(nil).AgentQueuedPromptsList), sessionID)
}

// AgentReadyErr mocks base method.
func (m *MockWorkspace) AgentReadyErr() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentReadyErr")
	ret0, _ := ret[0].(error)
	return ret0
}

// AgentReadyErr indicates an expected call of AgentReadyErr.
func (mr *MockWorkspaceMockRecorder) AgentReadyErr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentReadyErr", reflect.TypeOf((*MockWorkspace)(nil).AgentReadyErr))
}

// AgentRun mocks base method.
func (m *MockWorkspace) AgentRun(ctx context.Context, sessionID, prompt string, attachments ...message.Attachment) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sessionID, prompt}
	for _, a := range attachments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AgentRun", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AgentRun indicates an expected call of AgentRun.
func (mr *MockWorkspaceMockRecorder) AgentRun(ctx, sessionID, prompt any, attachments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sessionID, prompt}, attachments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentRun", reflect.TypeOf((*MockWorkspace)(nil).AgentRun), varargs...)
}

// AgentRunShellCommand mocks base method.
func (m *MockWorkspace) AgentRunShellCommand(ctx context.Context, sessionID, command string, termWidth int, onProgress func(string), isFirstMessage bool) (proto.ShellCommandResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentRunShellCommand", ctx, sessionID, command, termWidth, onProgress, isFirstMessage)
	ret0, _ := ret[0].(proto.ShellCommandResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AgentRunShellCommand indicates an expected call of AgentRunShellCommand.
func (mr *MockWorkspaceMockRecorder) AgentRunShellCommand(ctx, sessionID, command, termWidth, onProgress, isFirstMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentRunShellCommand", reflect.TypeOf((*MockWorkspace)(nil).AgentRunShellCommand), ctx, sessionID, command, termWidth, onProgress, isFirstMessage)
}

// AgentSummarize mocks base method.
func (m *MockWorkspace) AgentSummarize(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentSummarize", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AgentSummarize indicates an expected call of AgentSummarize.
func (mr *MockWorkspaceMockRecorder) AgentSummarize(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentSummarize", reflect.TypeOf((*MockWorkspace)(nil).AgentSummarize), ctx, sessionID)
}

// Config mocks base method.
func (m *MockWorkspace) Config() *config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*config.Config)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockWorkspaceMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockWorkspace)(nil).Config))
}

// CreateAgentToolSessionID mocks base method.
func (m *MockWorkspace) CreateAgentToolSessionID(messageID, toolCallID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgentToolSessionID", messageID, toolCallID)
	ret0, _ := ret[0].(string)
	return ret0
}

// CreateAgentToolSessionID indicates an expected call of CreateAgentToolSessionID.
func (mr *MockWorkspaceMockRecorder) CreateAgentToolSessionID(messageID, toolCallID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgentToolSessionID", reflect.TypeOf((*MockWorkspace)(nil).CreateAgentToolSessionID), messageID, toolCallID)
}

// CreateSession mocks base method.
func (m *MockWorkspace) CreateSession(ctx context.Context, title string) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, title)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockWorkspaceMockRecorder) CreateSession(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockWorkspace)(nil).CreateSession), ctx, title)
}

// DeleteSession mocks base method.
func (m *MockWorkspace) DeleteSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockWorkspaceMockRecorder) DeleteSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockWorkspace)(nil).DeleteSession), ctx, sessionID)
}

// DisableDockerMCP mocks base method.
func (m *MockWorkspace) DisableDockerMCP() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableDockerMCP")
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableDockerMCP indicates an expected call of DisableDockerMCP.
func (mr *MockWorkspaceMockRecorder) DisableDockerMCP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableDockerMCP", reflect.TypeOf((*MockWorkspace)(nil).DisableDockerMCP))
}

// EnableDockerMCP mocks base method.
func (m *MockWorkspace) EnableDockerMCP(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableDockerMCP", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableDockerMCP indicates an expected call of EnableDockerMCP.
func (mr *MockWorkspaceMockRecorder) EnableDockerMCP(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableDockerMCP", reflect.TypeOf((*MockWorkspace)(nil).EnableDockerMCP), ctx)
}

// FileTrackerLastReadTime mocks base method.
func (m *MockWorkspace) FileTrackerLastReadTime(ctx context.Context, sessionID, path string) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileTrackerLastReadTime", ctx, sessionID, path)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// FileTrackerLastReadTime indicates an expected call of FileTrackerLastReadTime.
func (mr *MockWorkspaceMockRecorder) FileTrackerLastReadTime(ctx, sessionID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileTrackerLastReadTime", reflect.TypeOf((*MockWorkspace)(nil).FileTrackerLastReadTime), ctx, sessionID, path)
}

// FileTrackerListReadFiles mocks base method.
func (m *MockWorkspace) FileTrackerListReadFiles(ctx context.Context, sessionID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileTrackerListReadFiles", ctx, sessionID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileTrackerListReadFiles indicates an expected call of FileTrackerListReadFiles.
func (mr *MockWorkspaceMockRecorder) FileTrackerListReadFiles(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileTrackerListReadFiles", reflect.TypeOf((*MockWorkspace)(nil).FileTrackerListReadFiles), ctx, sessionID)
}

// FileTrackerRecordRead mocks base method.
func (m *MockWorkspace) FileTrackerRecordRead(ctx context.Context, sessionID, path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FileTrackerRecordRead", ctx, sessionID, path)
}

// FileTrackerRecordRead indicates an expected call of FileTrackerRecordRead.
func (mr *MockWorkspaceMockRecorder) FileTrackerRecordRead(ctx, sessionID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileTrackerRecordRead", reflect.TypeOf((*MockWorkspace)(nil).FileTrackerRecordRead), ctx, sessionID, path)
}

// GetMCPPrompt mocks base method.
func (m *MockWorkspace) GetMCPPrompt(clientID, promptID string, args map[string]string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMCPPrompt", clientID, promptID, args)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMCPPrompt indicates an expected call of GetMCPPrompt.
func (mr *MockWorkspaceMockRecorder) GetMCPPrompt(clientID, promptID, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMCPPrompt", reflect.TypeOf((*MockWorkspace)(nil).GetMCPPrompt), clientID, promptID, args)
}

// GetSession mocks base method.
func (m *MockWorkspace) GetSession(ctx context.Context, sessionID string) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockWorkspaceMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockWorkspace)(nil).GetSession), ctx, sessionID)
}

// ImportCopilot mocks base method.
func (m *MockWorkspace) ImportCopilot() (*oauth.Token, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportCopilot")
	ret0, _ := ret[0].(*oauth.Token)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ImportCopilot indicates an expected call of ImportCopilot.
func (mr *MockWorkspaceMockRecorder) ImportCopilot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportCopilot", reflect.TypeOf((*MockWorkspace)(nil).ImportCopilot))
}

// InitCoderAgent mocks base method.
func (m *MockWorkspace) InitCoderAgent(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitCoderAgent", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitCoderAgent indicates an expected call of InitCoderAgent.
func (mr *MockWorkspaceMockRecorder) InitCoderAgent(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitCoderAgent", reflect.TypeOf((*MockWorkspace)(nil).InitCoderAgent), ctx)
}

// InitCoderAgentNonInteractive mocks base method.
func (m *MockWorkspace) InitCoderAgentNonInteractive(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitCoderAgentNonInteractive", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitCoderAgentNonInteractive indicates an expected call of InitCoderAgentNonInteractive.
func (mr *MockWorkspaceMockRecorder) InitCoderAgentNonInteractive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitCoderAgentNonInteractive", reflect.TypeOf((*MockWorkspace)(nil).InitCoderAgentNonInteractive), ctx)
}

// InitializePrompt mocks base method.
func (m *MockWorkspace) InitializePrompt() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializePrompt")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitializePrompt indicates an expected call of InitializePrompt.
func (mr *MockWorkspaceMockRecorder) InitializePrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializePrompt", reflect.TypeOf((*MockWorkspace)(nil).InitializePrompt))
}

// LSPGetDiagnosticCounts mocks base method.
func (m *MockWorkspace) LSPGetDiagnosticCounts(name string) lsp.DiagnosticCounts {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LSPGetDiagnosticCounts", name)
	ret0, _ := ret[0].(lsp.DiagnosticCounts)
	return ret0
}

// LSPGetDiagnosticCounts indicates an expected call of LSPGetDiagnosticCounts.
func (mr *MockWorkspaceMockRecorder) LSPGetDiagnosticCounts(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LSPGetDiagnosticCounts", reflect.TypeOf((*MockWorkspace)(nil).LSPGetDiagnosticCounts), name)
}

// LSPGetStates mocks base method.
func (m *MockWorkspace) LSPGetStates() map[string]workspace.LSPClientInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LSPGetStates")
	ret0, _ := ret[0].(map[string]workspace.LSPClientInfo)
	return ret0
}

// LSPGetStates indicates an expected call of LSPGetStates.
func (mr *MockWorkspaceMockRecorder) LSPGetStates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LSPGetStates", reflect.TypeOf((*MockWorkspace)(nil).LSPGetStates))
}

// LSPStart mocks base method.
func (m *MockWorkspace) LSPStart(ctx context.Context, path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LSPStart", ctx, path)
}

// LSPStart indicates an expected call of LSPStart.
func (mr *MockWorkspaceMockRecorder) LSPStart(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LSPStart", reflect.TypeOf((*MockWorkspace)(nil).LSPStart), ctx, path)
}

// LSPStopAll mocks base method.
func (m *MockWorkspace) LSPStopAll(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LSPStopAll", ctx)
}

// LSPStopAll indicates an expected call of LSPStopAll.
func (mr *MockWorkspaceMockRecorder) LSPStopAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LSPStopAll", reflect.TypeOf((*MockWorkspace)(nil).LSPStopAll), ctx)
}

// ListAllUserMessages mocks base method.
func (m *MockWorkspace) ListAllUserMessages(ctx context.Context) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUserMessages", ctx)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUserMessages indicates an expected call of ListAllUserMessages.
func (mr *MockWorkspaceMockRecorder) ListAllUserMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUserMessages", reflect.TypeOf((*MockWorkspace)(nil).ListAllUserMessages), ctx)
}

// ListMCPPrompts mocks base method.
func (m *MockWorkspace) ListMCPPrompts(ctx context.Context) ([]commands.MCPPrompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMCPPrompts", ctx)
	ret0, _ := ret[0].([]commands.MCPPrompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMCPPrompts indicates an expected call of ListMCPPrompts.
func (mr *MockWorkspaceMockRecorder) ListMCPPrompts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMCPPrompts", reflect.TypeOf((*MockWorkspace)(nil).ListMCPPrompts), ctx)
}

// ListMessages mocks base method.
func (m *MockWorkspace) ListMessages(ctx context.Context, sessionID string) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, sessionID)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockWorkspaceMockRecorder) ListMessages(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockWorkspace)(nil).ListMessages), ctx, sessionID)
}

// ListSessionHistory mocks base method.
func (m *MockWorkspace) ListSessionHistory(ctx context.Context, sessionID string) ([]history.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionHistory", ctx, sessionID)
	ret0, _ := ret[0].([]history.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionHistory indicates an expected call of ListSessionHistory.
func (mr *MockWorkspaceMockRecorder) ListSessionHistory(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionHistory", reflect.TypeOf((*MockWorkspace)(nil).ListSessionHistory), ctx, sessionID)
}

// ListSessions mocks base method.
func (m *MockWorkspace) ListSessions(ctx context.Context) ([]session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx)
	ret0, _ := ret[0].([]session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockWorkspaceMockRecorder) ListSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockWorkspace)(nil).ListSessions), ctx)
}

// ListSkills mocks base method.
func (m *MockWorkspace) ListSkills(ctx context.Context) ([]skills.CatalogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", ctx)
	ret0, _ := ret[0].([]skills.CatalogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockWorkspaceMockRecorder) ListSkills(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockWorkspace)(nil).ListSkills), ctx)
}

// ListUserMessages mocks base method.
func (m *MockWorkspace) ListUserMessages(ctx context.Context, sessionID string) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserMessages", ctx, sessionID)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserMessages indicates an expected call of ListUserMessages.
func (mr *MockWorkspaceMockRecorder) ListUserMessages(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserMessages", reflect.TypeOf((*MockWorkspace)(nil).ListUserMessages), ctx, sessionID)
}

// MCPAuthURL mocks base method.
func (m *MockWorkspace) MCPAuthURL(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MCPAuthURL", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// MCPAuthURL indicates an expected call of MCPAuthURL.
func (mr *MockWorkspaceMockRecorder) MCPAuthURL(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MCPAuthURL", reflect.TypeOf((*MockWorkspace)(nil).MCPAuthURL), name)
}

// MCPAuthenticate mocks base method.
func (m *MockWorkspace) MCPAuthenticate(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MCPAuthenticate", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// MCPAuthenticate indicates an expected call of MCPAuthenticate.
func (mr *MockWorkspaceMockRecorder) MCPAuthenticate(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MCPAuthenticate", reflect.TypeOf((*MockWorkspace)(nil).MCPAuthenticate), ctx, name)
}

// MCPGetStates mocks base method.
func (m *MockWorkspace) MCPGetStates() map[string]mcp.ClientInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MCPGetStates")
	ret0, _ := ret[0].(map[string]mcp.ClientInfo)
	return ret0
}

// MCPGetStates indicates an expected call of MCPGetStates.
func (mr *MockWorkspaceMockRecorder) MCPGetStates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MCPGetStates", reflect.TypeOf((*MockWorkspace)(nil).MCPGetStates))
}

// MCPPendingAuth mocks base method.
func (m *MockWorkspace) MCPPendingAuth() []mcp.PendingAuthServer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MCPPendingAuth")
	ret0, _ := ret[0].([]mcp.PendingAuthServer)
	return ret0
}

// MCPPendingAuth indicates an expected call of MCPPendingAuth.
func (mr *MockWorkspaceMockRecorder) MCPPendingAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MCPPendingAuth", reflect.TypeOf((*MockWorkspace)(nil).MCPPendingAuth))
}

// MCPRefreshPrompts mocks base method.
func (m *MockWorkspace) MCPRefreshPrompts(ctx context.Context, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MCPRefreshPrompts", ctx, name)
}

// MCPRefreshPrompts indicates an expected call of MCPRefreshPrompts.
func (mr *MockWorkspaceMockRecorder) MCPRefreshPrompts(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MCPRefreshPrompts", reflect.TypeOf((*MockWorkspace)(nil).MCPRefreshPrompts), ctx, name)
}

// MCPRefreshResources mocks base method.
func (m *MockWorkspace) MCPRefreshResources(ctx context.Context, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MCPRefreshResources", ctx, name)
}

// MCPRefreshResources indicates an expected call of MCPRefreshResources.
func (mr *MockWorkspaceMockRecorder) MCPRefreshResources(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MCPRefreshResources", reflect.TypeOf((*MockWorkspace)(nil).MCPRefreshResources), ctx, name)
}

// MarkProjectInitialized mocks base method.
func (m *MockWorkspace) MarkProjectInitialized() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProjectInitialized")
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProjectInitialized indicates an expected call of MarkProjectInitialized.
func (mr *MockWorkspaceMockRecorder) MarkProjectInitialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProjectInitialized", reflect.TypeOf((*MockWorkspace)(nil).MarkProjectInitialized))
}

// ParseAgentToolSessionID mocks base method.
func (m *MockWorkspace) ParseAgentToolSessionID(sessionID string) (string, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAgentToolSessionID", sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// ParseAgentToolSessionID indicates an expected call of ParseAgentToolSessionID.
func (mr *MockWorkspaceMockRecorder) ParseAgentToolSessionID(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAgentToolSessionID", reflect.TypeOf((*MockWorkspace)(nil).ParseAgentToolSessionID), sessionID)
}

// PermissionDeny mocks base method.
func (m *MockWorkspace) PermissionDeny(perm permission.PermissionRequest) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionDeny", perm)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PermissionDeny indicates an expected call of PermissionDeny.
func (mr *MockWorkspaceMockRecorder) PermissionDeny(perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionDeny", reflect.TypeOf((*MockWorkspace)(nil).PermissionDeny), perm)
}

// PermissionGrant mocks base method.
func (m *MockWorkspace) PermissionGrant(perm permission.PermissionRequest) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionGrant", perm)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PermissionGrant indicates an expected call of PermissionGrant.
func (mr *MockWorkspaceMockRecorder) PermissionGrant(perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionGrant", reflect.TypeOf((*MockWorkspace)(nil).PermissionGrant), perm)
}

// PermissionGrantPersistent mocks base method.
func (m *MockWorkspace) PermissionGrantPersistent(perm permission.PermissionRequest) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionGrantPersistent", perm)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PermissionGrantPersistent indicates an expected call of PermissionGrantPersistent.
func (mr *MockWorkspaceMockRecorder) PermissionGrantPersistent(perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionGrantPersistent", reflect.TypeOf((*MockWorkspace)(nil).PermissionGrantPersistent), perm)
}

// PermissionMode mocks base method.
func (m *MockWorkspace) PermissionMode() permission.PermissionMode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionMode")
	ret0, _ := ret[0].(permission.PermissionMode)
	return ret0
}

// PermissionMode indicates an expected call of PermissionMode.
func (mr *MockWorkspaceMockRecorder) PermissionMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionMode", reflect.TypeOf((*MockWorkspace)(nil).PermissionMode))
}

// PermissionSetMode mocks base method.
func (m *MockWorkspace) PermissionSetMode(mode permission.PermissionMode) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PermissionSetMode", mode)
}

// PermissionSetMode indicates an expected call of PermissionSetMode.
func (mr *MockWorkspaceMockRecorder) PermissionSetMode(mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionSetMode", reflect.TypeOf((*MockWorkspace)(nil).PermissionSetMode), mode)
}

// PreviewUndo mocks base method.
func (m *MockWorkspace) PreviewUndo(ctx context.Context, sessionID string) (undo.Preview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewUndo", ctx, sessionID)
	ret0, _ := ret[0].(undo.Preview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewUndo indicates an expected call of PreviewUndo.
func (mr *MockWorkspaceMockRecorder) PreviewUndo(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewUndo", reflect.TypeOf((*MockWorkspace)(nil).PreviewUndo), ctx, sessionID)
}

// ProjectNeedsInitialization mocks base method.
func (m *MockWorkspace) ProjectNeedsInitialization() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectNeedsInitialization")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProjectNeedsInitialization indicates an expected call of ProjectNeedsInitialization.
func (mr *MockWorkspaceMockRecorder) ProjectNeedsInitialization() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectNeedsInitialization", reflect.TypeOf((*MockWorkspace)(nil).ProjectNeedsInitialization))
}

// PruneRecentModels mocks base method.
func (m *MockWorkspace) PruneRecentModels(scope config.Scope, name config.ModelConfigName, stale []config.SelectedModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneRecentModels", scope, name, stale)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneRecentModels indicates an expected call of PruneRecentModels.
func (mr *MockWorkspaceMockRecorder) PruneRecentModels(scope, name, stale any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneRecentModels", reflect.TypeOf((*MockWorkspace)(nil).PruneRecentModels), scope, name, stale)
}

// QuestionAnswer mocks base method.
func (m *MockWorkspace) QuestionAnswer(responses []question.Answer) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuestionAnswer", responses)
	ret0, _ := ret[0].(bool)
	return ret0
}

// QuestionAnswer indicates an expected call of QuestionAnswer.
func (mr *MockWorkspaceMockRecorder) QuestionAnswer(responses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionAnswer", reflect.TypeOf((*MockWorkspace)(nil).QuestionAnswer), responses)
}

// QuestionCancel mocks base method.
func (m *MockWorkspace) QuestionCancel() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuestionCancel")
	ret0, _ := ret[0].(bool)
	return ret0
}

// QuestionCancel indicates an expected call of QuestionCancel.
func (mr *MockWorkspaceMockRecorder) QuestionCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionCancel", reflect.TypeOf((*MockWorkspace)(nil).QuestionCancel))
}

// ReadMCPResource mocks base method.
func (m *MockWorkspace) ReadMCPResource(ctx context.Context, name, uri string) ([]workspace.MCPResourceContents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMCPResource", ctx, name, uri)
	ret0, _ := ret[0].([]workspace.MCPResourceContents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMCPResource indicates an expected call of ReadMCPResource.
func (mr *MockWorkspaceMockRecorder) ReadMCPResource(ctx, name, uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMCPResource", reflect.TypeOf((*MockWorkspace)(nil).ReadMCPResource), ctx, name, uri)
}

// ReadSkill mocks base method.
func (m *MockWorkspace) ReadSkill(ctx context.Context, skillID string) ([]byte, skills.SkillReadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSkill", ctx, skillID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(skills.SkillReadResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadSkill indicates an expected call of ReadSkill.
func (mr *MockWorkspaceMockRecorder) ReadSkill(ctx, skillID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSkill", reflect.TypeOf((*MockWorkspace)(nil).ReadSkill), ctx, skillID)
}

// RecordRecentModel mocks base method.
func (m *MockWorkspace) RecordRecentModel(scope config.Scope, name config.ModelConfigName, model config.SelectedModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRecentModel", scope, name, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRecentModel indicates an expected call of RecordRecentModel.
func (mr *MockWorkspaceMockRecorder) RecordRecentModel(scope, name, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRecentModel", reflect.TypeOf((*MockWorkspace)(nil).RecordRecentModel), scope, name, model)
}

// RefreshMCPTools mocks base method.
func (m *MockWorkspace) RefreshMCPTools(ctx context.Context, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RefreshMCPTools", ctx, name)
}

// RefreshMCPTools indicates an expected call of RefreshMCPTools.
func (mr *MockWorkspaceMockRecorder) RefreshMCPTools(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshMCPTools", reflect.TypeOf((*MockWorkspace)(nil).RefreshMCPTools), ctx, name)
}

// RefreshOAuthToken mocks base method.
func (m *MockWorkspace) RefreshOAuthToken(ctx context.Context, scope config.Scope, providerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshOAuthToken", ctx, scope, providerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshOAuthToken indicates an expected call of RefreshOAuthToken.
func (mr *MockWorkspaceMockRecorder) RefreshOAuthToken(ctx, scope, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshOAuthToken", reflect.TypeOf((*MockWorkspace)(nil).RefreshOAuthToken), ctx, scope, providerID)
}

// RemoveConfigField mocks base method.
func (m *MockWorkspace) RemoveConfigField(scope config.Scope, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveConfigField", scope, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveConfigField indicates an expected call of RemoveConfigField.
func (mr *MockWorkspaceMockRecorder) RemoveConfigField(scope, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveConfigField", reflect.TypeOf((*MockWorkspace)(nil).RemoveConfigField), scope, key)
}

// Resolver mocks base method.
func (m *MockWorkspace) Resolver() config.VariableResolver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolver")
	ret0, _ := ret[0].(config.VariableResolver)
	return ret0
}

// Resolver indicates an expected call of Resolver.
func (mr *MockWorkspaceMockRecorder) Resolver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolver", reflect.TypeOf((*MockWorkspace)(nil).Resolver))
}

// SaveSession mocks base method.
func (m *MockWorkspace) SaveSession(ctx context.Context, sess session.Session) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", ctx, sess)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockWorkspaceMockRecorder) SaveSession(ctx, sess any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockWorkspace)(nil).SaveSession), ctx, sess)
}

// SetCompactMode mocks base method.
func (m *MockWorkspace) SetCompactMode(scope config.Scope, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCompactMode", scope, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCompactMode indicates an expected call of SetCompactMode.
func (mr *MockWorkspaceMockRecorder) SetCompactMode(scope, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompactMode", reflect.TypeOf((*MockWorkspace)(nil).SetCompactMode), scope, enabled)
}

// SetConfigField mocks base method.
func (m *MockWorkspace) SetConfigField(scope config.Scope, key string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConfigField", scope, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConfigField indicates an expected call of SetConfigField.
func (mr *MockWorkspaceMockRecorder) SetConfigField(scope, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfigField", reflect.TypeOf((*MockWorkspace)(nil).SetConfigField), scope, key, value)
}

// SetCurrentSession mocks base method.
func (m *MockWorkspace) SetCurrentSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCurrentSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCurrentSession indicates an expected call of SetCurrentSession.
func (mr *MockWorkspaceMockRecorder) SetCurrentSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentSession", reflect.TypeOf((*MockWorkspace)(nil).SetCurrentSession), ctx, sessionID)
}

// SetProviderAPIKey mocks base method.
func (m *MockWorkspace) SetProviderAPIKey(scope config.Scope, providerID string, apiKey any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderAPIKey", scope, providerID, apiKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProviderAPIKey indicates an expected call of SetProviderAPIKey.
func (mr *MockWorkspaceMockRecorder) SetProviderAPIKey(scope, providerID, apiKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderAPIKey", reflect.TypeOf((*MockWorkspace)(nil).SetProviderAPIKey), scope, providerID, apiKey)
}

// Shutdown mocks base method.
func (m *MockWorkspace) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockWorkspaceMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockWorkspace)(nil).Shutdown))
}

// Subscribe mocks base method.
func (m *MockWorkspace) Subscribe(program *tea.Program) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", program)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockWorkspaceMockRecorder) Subscribe(program any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockWorkspace)(nil).Subscribe), program)
}

// Undo mocks base method.
func (m *MockWorkspace) Undo(ctx context.Context, sessionID, cutMessageID string) (undo.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undo", ctx, sessionID, cutMessageID)
	ret0, _ := ret[0].(undo.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Undo indicates an expected call of Undo.
func (mr *MockWorkspaceMockRecorder) Undo(ctx, sessionID, cutMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undo", reflect.TypeOf((*MockWorkspace)(nil).Undo), ctx, sessionID, cutMessageID)
}

// UpdateAgentModel mocks base method.
func (m *MockWorkspace) UpdateAgentModel(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentModel", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAgentModel indicates an expected call of UpdateAgentModel.
func (mr *MockWorkspaceMockRecorder) UpdateAgentModel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentModel", reflect.TypeOf((*MockWorkspace)(nil).UpdateAgentModel), ctx)
}

// UpdatePreferredModel mocks base method.
func (m *MockWorkspace) UpdatePreferredModel(scope config.Scope, name config.ModelConfigName, model config.SelectedModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreferredModel", scope, name, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePreferredModel indicates an expected call of UpdatePreferredModel.
func (mr *MockWorkspaceMockRecorder) UpdatePreferredModel(scope, name, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreferredModel", reflect.TypeOf((*MockWorkspace)(nil).UpdatePreferredModel), scope, name, model)
}

// UpsertProviderModel mocks base method.
func (m *MockWorkspace) UpsertProviderModel(scope config.Scope, providerID string, model catwalk.Model) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProviderModel", scope, providerID, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertProviderModel indicates an expected call of UpsertProviderModel.
func (mr *MockWorkspaceMockRecorder) UpsertProviderModel(scope, providerID, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProviderModel", reflect.TypeOf((*MockWorkspace)(nil).UpsertProviderModel), scope, providerID, model)
}

// WorkingDir mocks base method.
func (m *MockWorkspace) WorkingDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkingDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// WorkingDir indicates an expected call of WorkingDir.
func (mr *MockWorkspaceMockRecorder) WorkingDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkingDir", reflect.TypeOf((*MockWorkspace)(nil).WorkingDir))
}
