// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/ui/common (interfaces: WheelScrollable)
//
// Generated by this command:
//
//	mockgen -destination=internal/ui/model/mock_wheel_scrollable_test.go -package=model github.com/NaturalSelect/angela/internal/ui/common WheelScrollable
//

// Package model is a generated GoMock package.
package model

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWheelScrollable is a mock of WheelScrollable interface.
type MockWheelScrollable struct {
	ctrl     *gomock.Controller
	recorder *MockWheelScrollableMockRecorder
	isgomock struct{}
}

// MockWheelScrollableMockRecorder is the mock recorder for MockWheelScrollable.
type MockWheelScrollableMockRecorder struct {
	mock *MockWheelScrollable
}

// NewMockWheelScrollable creates a new mock instance.
func NewMockWheelScrollable(ctrl *gomock.Controller) *MockWheelScrollable {
	mock := &MockWheelScrollable{ctrl: ctrl}
	mock.recorder = &MockWheelScrollableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWheelScrollable) EXPECT() *MockWheelScrollableMockRecorder {
	return m.recorder
}

// HandleWheel mocks base method.
func (m *MockWheelScrollable) HandleWheel(deltaX, deltaY float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleWheel", deltaX, deltaY)
}

// HandleWheel indicates an expected call of HandleWheel.
func (mr *MockWheelScrollableMockRecorder) HandleWheel(deltaX, deltaY any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWheel", reflect.TypeOf((*MockWheelScrollable)(nil).HandleWheel), deltaX, deltaY)
}
