// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/ui/dialog (interfaces: MouseClickableEditor,PasteableEditor)
//
// Generated by this command:
//
//	mockgen -destination=internal/ui/model/mock_inline_editor_test.go -package=model github.com/NaturalSelect/angela/internal/ui/dialog MouseClickableEditor,PasteableEditor
//

// Package model is a generated GoMock package.
package model

import (
	reflect "reflect"

	key "charm.land/bubbles/v2/key"
	tea "charm.land/bubbletea/v2"
	uv "github.com/charmbracelet/ultraviolet"
	gomock "go.uber.org/mock/gomock"
)

// MockMouseClickableEditor is a mock of MouseClickableEditor interface.
type MockMouseClickableEditor struct {
	ctrl     *gomock.Controller
	recorder *MockMouseClickableEditorMockRecorder
	isgomock struct{}
}

// MockMouseClickableEditorMockRecorder is the mock recorder for MockMouseClickableEditor.
type MockMouseClickableEditorMockRecorder struct {
	mock *MockMouseClickableEditor
}

// NewMockMouseClickableEditor creates a new mock instance.
func NewMockMouseClickableEditor(ctrl *gomock.Controller) *MockMouseClickableEditor {
	mock := &MockMouseClickableEditor{ctrl: ctrl}
	mock.recorder = &MockMouseClickableEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMouseClickableEditor) EXPECT() *MockMouseClickableEditorMockRecorder {
	return m.recorder
}

// Draw mocks base method.
func (m *MockMouseClickableEditor) Draw(scr uv.Screen, area uv.Rectangle) *tea.Cursor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Draw", scr, area)
	ret0, _ := ret[0].(*tea.Cursor)
	return ret0
}

// Draw indicates an expected call of Draw.
func (mr *MockMouseClickableEditorMockRecorder) Draw(scr, area any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockMouseClickableEditor)(nil).Draw), scr, area)
}

// HandleKey mocks base method.
func (m *MockMouseClickableEditor) HandleKey(msg tea.KeyPressMsg) (bool, tea.Cmd) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleKey", msg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(tea.Cmd)
	return ret0, ret1
}

// HandleKey indicates an expected call of HandleKey.
func (mr *MockMouseClickableEditorMockRecorder) HandleKey(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleKey", reflect.TypeOf((*MockMouseClickableEditor)(nil).HandleKey), msg)
}

// HandleMouseClick mocks base method.
func (m *MockMouseClickableEditor) HandleMouseClick(x, y int) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMouseClick", x, y)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// HandleMouseClick indicates an expected call of HandleMouseClick.
func (mr *MockMouseClickableEditorMockRecorder) HandleMouseClick(x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMouseClick", reflect.TypeOf((*MockMouseClickableEditor)(nil).HandleMouseClick), x, y)
}

// Height mocks base method.
func (m *MockMouseClickableEditor) Height(width int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Height", width)
	ret0, _ := ret[0].(int)
	return ret0
}

// Height indicates an expected call of Height.
func (mr *MockMouseClickableEditorMockRecorder) Height(width any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Height", reflect.TypeOf((*MockMouseClickableEditor)(nil).Height), width)
}

// HeightChanged mocks base method.
func (m *MockMouseClickableEditor) HeightChanged() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeightChanged")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HeightChanged indicates an expected call of HeightChanged.
func (mr *MockMouseClickableEditorMockRecorder) HeightChanged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeightChanged", reflect.TypeOf((*MockMouseClickableEditor)(nil).HeightChanged))
}

// SetFocused mocks base method.
func (m *MockMouseClickableEditor) SetFocused(focused bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFocused", focused)
}

// SetFocused indicates an expected call of SetFocused.
func (mr *MockMouseClickableEditorMockRecorder) SetFocused(focused any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocused", reflect.TypeOf((*MockMouseClickableEditor)(nil).SetFocused), focused)
}

// SetHover mocks base method.
func (m *MockMouseClickableEditor) SetHover(x, y int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHover", x, y)
}

// SetHover indicates an expected call of SetHover.
func (mr *MockMouseClickableEditorMockRecorder) SetHover(x, y any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHover", reflect.TypeOf((*MockMouseClickableEditor)(nil).SetHover), x, y)
}

// ShortHelp mocks base method.
func (m *MockMouseClickableEditor) ShortHelp() []key.Binding {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortHelp")
	ret0, _ := ret[0].([]key.Binding)
	return ret0
}

// ShortHelp indicates an expected call of ShortHelp.
func (mr *MockMouseClickableEditorMockRecorder) ShortHelp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortHelp", reflect.TypeOf((*MockMouseClickableEditor)(nil).ShortHelp))
}

// MockPasteableEditor is a mock of PasteableEditor interface.
type MockPasteableEditor struct {
	ctrl     *gomock.Controller
	recorder *MockPasteableEditorMockRecorder
	isgomock struct{}
}

// MockPasteableEditorMockRecorder is the mock recorder for MockPasteableEditor.
type MockPasteableEditorMockRecorder struct {
	mock *MockPasteableEditor
}

// NewMockPasteableEditor creates a new mock instance.
func NewMockPasteableEditor(ctrl *gomock.Controller) *MockPasteableEditor {
	mock := &MockPasteableEditor{ctrl: ctrl}
	mock.recorder = &MockPasteableEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasteableEditor) EXPECT() *MockPasteableEditorMockRecorder {
	return m.recorder
}

// HandlePaste mocks base method.
func (m *MockPasteableEditor) HandlePaste(msg tea.PasteMsg) tea.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePaste", msg)
	ret0, _ := ret[0].(tea.Cmd)
	return ret0
}

// HandlePaste indicates an expected call of HandlePaste.
func (mr *MockPasteableEditorMockRecorder) HandlePaste(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePaste", reflect.TypeOf((*MockPasteableEditor)(nil).HandlePaste), msg)
}
