// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/update (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=internal/update/mock_client_test.go -package=update github.com/NaturalSelect/angela/internal/update Client
//

// Package update is a generated GoMock package.
package update

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Latest mocks base method.
func (m *MockClient) Latest(ctx context.Context) (*Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", ctx)
	ret0, _ := ret[0].(*Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Latest indicates an expected call of Latest.
func (mr *MockClientMockRecorder) Latest(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*MockClient)(nil).Latest), ctx)
}
