// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/history (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/workspace/mock_historyservice_test.go -package=workspace -mock_names=Service=MockHistoryService github.com/NaturalSelect/angela/internal/history Service
//

// Package workspace is a generated GoMock package.
package workspace

import (
	context "context"
	reflect "reflect"

	history "github.com/NaturalSelect/angela/internal/history"
	pubsub "github.com/NaturalSelect/angela/internal/pubsub"
	gomock "go.uber.org/mock/gomock"
)

// MockHistoryService is a mock of Service interface.
type MockHistoryService struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryServiceMockRecorder
	isgomock struct{}
}

// MockHistoryServiceMockRecorder is the mock recorder for MockHistoryService.
type MockHistoryServiceMockRecorder struct {
	mock *MockHistoryService
}

// NewMockHistoryService creates a new mock instance.
func NewMockHistoryService(ctrl *gomock.Controller) *MockHistoryService {
	mock := &MockHistoryService{ctrl: ctrl}
	mock.recorder = &MockHistoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryService) EXPECT() *MockHistoryServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHistoryService) Create(ctx context.Context, sessionID, path, content string) (history.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, sessionID, path, content)
	ret0, _ := ret[0].(history.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockHistoryServiceMockRecorder) Create(ctx, sessionID, path, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHistoryService)(nil).Create), ctx, sessionID, path, content)
}

// CreateVersion mocks base method.
func (m *MockHistoryService) CreateVersion(ctx context.Context, sessionID, path, content string) (history.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVersion", ctx, sessionID, path, content)
	ret0, _ := ret[0].(history.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVersion indicates an expected call of CreateVersion.
func (mr *MockHistoryServiceMockRecorder) CreateVersion(ctx, sessionID, path, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVersion", reflect.TypeOf((*MockHistoryService)(nil).CreateVersion), ctx, sessionID, path, content)
}

// Delete mocks base method.
func (m *MockHistoryService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHistoryServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHistoryService)(nil).Delete), ctx, id)
}

// DeleteSessionFiles mocks base method.
func (m *MockHistoryService) DeleteSessionFiles(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionFiles", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionFiles indicates an expected call of DeleteSessionFiles.
func (mr *MockHistoryServiceMockRecorder) DeleteSessionFiles(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionFiles", reflect.TypeOf((*MockHistoryService)(nil).DeleteSessionFiles), ctx, sessionID)
}

// Get mocks base method.
func (m *MockHistoryService) Get(ctx context.Context, id string) (history.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(history.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHistoryServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHistoryService)(nil).Get), ctx, id)
}

// GetByPathAndSession mocks base method.
func (m *MockHistoryService) GetByPathAndSession(ctx context.Context, path, sessionID string) (history.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPathAndSession", ctx, path, sessionID)
	ret0, _ := ret[0].(history.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPathAndSession indicates an expected call of GetByPathAndSession.
func (mr *MockHistoryServiceMockRecorder) GetByPathAndSession(ctx, path, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPathAndSession", reflect.TypeOf((*MockHistoryService)(nil).GetByPathAndSession), ctx, path, sessionID)
}

// ListBySession mocks base method.
func (m *MockHistoryService) ListBySession(ctx context.Context, sessionID string) ([]history.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySession", ctx, sessionID)
	ret0, _ := ret[0].([]history.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySession indicates an expected call of ListBySession.
func (mr *MockHistoryServiceMockRecorder) ListBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySession", reflect.TypeOf((*MockHistoryService)(nil).ListBySession), ctx, sessionID)
}

// ListLatestSessionFiles mocks base method.
func (m *MockHistoryService) ListLatestSessionFiles(ctx context.Context, sessionID string) ([]history.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLatestSessionFiles", ctx, sessionID)
	ret0, _ := ret[0].([]history.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLatestSessionFiles indicates an expected call of ListLatestSessionFiles.
func (mr *MockHistoryServiceMockRecorder) ListLatestSessionFiles(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLatestSessionFiles", reflect.TypeOf((*MockHistoryService)(nil).ListLatestSessionFiles), ctx, sessionID)
}

// Subscribe mocks base method.
func (m *MockHistoryService) Subscribe(arg0 context.Context) <-chan pubsub.Event[history.File] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0)
	ret0, _ := ret[0].(<-chan pubsub.Event[history.File])
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockHistoryServiceMockRecorder) Subscribe(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockHistoryService)(nil).Subscribe), arg0)
}
