// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/message (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/workspace/mock_messageservice_test.go -package=workspace -mock_names=Service=MockMessageService github.com/NaturalSelect/angela/internal/message Service
//

// Package workspace is a generated GoMock package.
package workspace

import (
	context "context"
	reflect "reflect"

	message "github.com/NaturalSelect/angela/internal/message"
	pubsub "github.com/NaturalSelect/angela/internal/pubsub"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageService is a mock of Service interface.
type MockMessageService struct {
	ctrl     *gomock.Controller
	recorder *MockMessageServiceMockRecorder
	isgomock struct{}
}

// MockMessageServiceMockRecorder is the mock recorder for MockMessageService.
type MockMessageServiceMockRecorder struct {
	mock *MockMessageService
}

// NewMockMessageService creates a new mock instance.
func NewMockMessageService(ctrl *gomock.Controller) *MockMessageService {
	mock := &MockMessageService{ctrl: ctrl}
	mock.recorder = &MockMessageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageService) EXPECT() *MockMessageServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageService) Create(ctx context.Context, sessionID string, params message.CreateMessageParams) (message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, sessionID, params)
	ret0, _ := ret[0].(message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMessageServiceMockRecorder) Create(ctx, sessionID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageService)(nil).Create), ctx, sessionID, params)
}

// Delete mocks base method.
func (m *MockMessageService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMessageServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMessageService)(nil).Delete), ctx, id)
}

// DeleteSessionMessages mocks base method.
func (m *MockMessageService) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionMessages", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionMessages indicates an expected call of DeleteSessionMessages.
func (mr *MockMessageServiceMockRecorder) DeleteSessionMessages(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionMessages", reflect.TypeOf((*MockMessageService)(nil).DeleteSessionMessages), ctx, sessionID)
}

// Flush mocks base method.
func (m *MockMessageService) Flush(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockMessageServiceMockRecorder) Flush(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockMessageService)(nil).Flush), ctx, id)
}

// FlushAll mocks base method.
func (m *MockMessageService) FlushAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushAll indicates an expected call of FlushAll.
func (mr *MockMessageServiceMockRecorder) FlushAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushAll", reflect.TypeOf((*MockMessageService)(nil).FlushAll), ctx)
}

// ForkSession mocks base method.
func (m *MockMessageService) ForkSession(ctx context.Context, srcSessionID, dstSessionID, sinceMessageID, beforeMessageID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForkSession", ctx, srcSessionID, dstSessionID, sinceMessageID, beforeMessageID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForkSession indicates an expected call of ForkSession.
func (mr *MockMessageServiceMockRecorder) ForkSession(ctx, srcSessionID, dstSessionID, sinceMessageID, beforeMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForkSession", reflect.TypeOf((*MockMessageService)(nil).ForkSession), ctx, srcSessionID, dstSessionID, sinceMessageID, beforeMessageID)
}

// Get mocks base method.
func (m *MockMessageService) Get(ctx context.Context, id string) (message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMessageServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMessageService)(nil).Get), ctx, id)
}

// GetLastAssistantMessage mocks base method.
func (m *MockMessageService) GetLastAssistantMessage(ctx context.Context, sessionID string) (message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastAssistantMessage", ctx, sessionID)
	ret0, _ := ret[0].(message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastAssistantMessage indicates an expected call of GetLastAssistantMessage.
func (mr *MockMessageServiceMockRecorder) GetLastAssistantMessage(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastAssistantMessage", reflect.TypeOf((*MockMessageService)(nil).GetLastAssistantMessage), ctx, sessionID)
}

// List mocks base method.
func (m *MockMessageService) List(ctx context.Context, sessionID string) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, sessionID)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMessageServiceMockRecorder) List(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMessageService)(nil).List), ctx, sessionID)
}

// ListAllUserMessages mocks base method.
func (m *MockMessageService) ListAllUserMessages(ctx context.Context) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUserMessages", ctx)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUserMessages indicates an expected call of ListAllUserMessages.
func (mr *MockMessageServiceMockRecorder) ListAllUserMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUserMessages", reflect.TypeOf((*MockMessageService)(nil).ListAllUserMessages), ctx)
}

// ListUserMessages mocks base method.
func (m *MockMessageService) ListUserMessages(ctx context.Context, sessionID string) ([]message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserMessages", ctx, sessionID)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserMessages indicates an expected call of ListUserMessages.
func (mr *MockMessageServiceMockRecorder) ListUserMessages(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserMessages", reflect.TypeOf((*MockMessageService)(nil).ListUserMessages), ctx, sessionID)
}

// Subscribe mocks base method.
func (m *MockMessageService) Subscribe(arg0 context.Context) <-chan pubsub.Event[message.Message] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0)
	ret0, _ := ret[0].(<-chan pubsub.Event[message.Message])
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockMessageServiceMockRecorder) Subscribe(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMessageService)(nil).Subscribe), arg0)
}

// Update mocks base method.
func (m *MockMessageService) Update(ctx context.Context, arg1 message.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMessageServiceMockRecorder) Update(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMessageService)(nil).Update), ctx, arg1)
}
