// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/undo (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/workspace/mock_undoservice_test.go -package=workspace -mock_names=Service=MockUndoService github.com/NaturalSelect/angela/internal/undo Service
//

// Package workspace is a generated GoMock package.
package workspace

import (
	context "context"
	reflect "reflect"

	undo "github.com/NaturalSelect/angela/internal/undo"
	gomock "go.uber.org/mock/gomock"
)

// MockUndoService is a mock of Service interface.
type MockUndoService struct {
	ctrl     *gomock.Controller
	recorder *MockUndoServiceMockRecorder
	isgomock struct{}
}

// MockUndoServiceMockRecorder is the mock recorder for MockUndoService.
type MockUndoServiceMockRecorder struct {
	mock *MockUndoService
}

// NewMockUndoService creates a new mock instance.
func NewMockUndoService(ctrl *gomock.Controller) *MockUndoService {
	mock := &MockUndoService{ctrl: ctrl}
	mock.recorder = &MockUndoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUndoService) EXPECT() *MockUndoServiceMockRecorder {
	return m.recorder
}

// Preview mocks base method.
func (m *MockUndoService) Preview(ctx context.Context, sessionID string) (undo.Preview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", ctx, sessionID)
	ret0, _ := ret[0].(undo.Preview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockUndoServiceMockRecorder) Preview(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockUndoService)(nil).Preview), ctx, sessionID)
}

// Undo mocks base method.
func (m *MockUndoService) Undo(ctx context.Context, sessionID, cutMessageID string) (undo.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undo", ctx, sessionID, cutMessageID)
	ret0, _ := ret[0].(undo.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Undo indicates an expected call of Undo.
func (mr *MockUndoServiceMockRecorder) Undo(ctx, sessionID, cutMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undo", reflect.TypeOf((*MockUndoService)(nil).Undo), ctx, sessionID, cutMessageID)
}
