// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/ui/dialog (interfaces: Dialog)
//
// Generated by this command:
//
//	mockgen -destination=internal/ui/dialog/mock_dialog_test.go -package=dialog github.com/NaturalSelect/angela/internal/ui/dialog Dialog
//

// Package dialog is a generated GoMock package.
package dialog

import (
	reflect "reflect"

	tea "charm.land/bubbletea/v2"
	uv "github.com/charmbracelet/ultraviolet"
	gomock "go.uber.org/mock/gomock"
)

// MockDialog is a mock of Dialog interface.
type MockDialog struct {
	ctrl     *gomock.Controller
	recorder *MockDialogMockRecorder
	isgomock struct{}
}

// MockDialogMockRecorder is the mock recorder for MockDialog.
type MockDialogMockRecorder struct {
	mock *MockDialog
}

// NewMockDialog creates a new mock instance.
func NewMockDialog(ctrl *gomock.Controller) *MockDialog {
	mock := &MockDialog{ctrl: ctrl}
	mock.recorder = &MockDialogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialog) EXPECT() *MockDialogMockRecorder {
	return m.recorder
}

// Draw mocks base method.
func (m *MockDialog) Draw(scr uv.Screen, area uv.Rectangle) *tea.Cursor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Draw", scr, area)
	ret0, _ := ret[0].(*tea.Cursor)
	return ret0
}

// Draw indicates an expected call of Draw.
func (mr *MockDialogMockRecorder) Draw(scr, area any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockDialog)(nil).Draw), scr, area)
}

// HandleMsg mocks base method.
func (m *MockDialog) HandleMsg(msg tea.Msg) Action {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMsg", msg)
	ret0, _ := ret[0].(Action)
	return ret0
}

// HandleMsg indicates an expected call of HandleMsg.
func (mr *MockDialogMockRecorder) HandleMsg(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMsg", reflect.TypeOf((*MockDialog)(nil).HandleMsg), msg)
}

// ID mocks base method.
func (m *MockDialog) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockDialogMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockDialog)(nil).ID))
}
