// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/agent (interfaces: Coordinator)
//
// Generated by this command:
//
//	mockgen -destination=internal/server/mock_coordinator_test.go -package=server github.com/NaturalSelect/angela/internal/agent Coordinator
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	fantasy "charm.land/fantasy"
	agent "github.com/NaturalSelect/angela/internal/agent"
	config "github.com/NaturalSelect/angela/internal/config"
	message "github.com/NaturalSelect/angela/internal/message"
	gomock "go.uber.org/mock/gomock"
)

// MockCoordinator is a mock of Coordinator interface.
type MockCoordinator struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinatorMockRecorder
	isgomock struct{}
}

// MockCoordinatorMockRecorder is the mock recorder for MockCoordinator.
type MockCoordinatorMockRecorder struct {
	mock *MockCoordinator
}

// NewMockCoordinator creates a new mock instance.
func NewMockCoordinator(ctrl *gomock.Controller) *MockCoordinator {
	mock := &MockCoordinator{ctrl: ctrl}
	mock.recorder = &MockCoordinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinator) EXPECT() *MockCoordinatorMockRecorder {
	return m.recorder
}

// AbandonBranch mocks base method.
func (m *MockCoordinator) AbandonBranch(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbandonBranch", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AbandonBranch indicates an expected call of AbandonBranch.
func (mr *MockCoordinatorMockRecorder) AbandonBranch(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbandonBranch", reflect.TypeOf((*MockCoordinator)(nil).AbandonBranch), sessionID)
}

// ActiveAgent mocks base method.
func (m *MockCoordinator) ActiveAgent(ctx context.Context, sessionID string) (config.ActiveAgent, agent.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveAgent", ctx, sessionID)
	ret0, _ := ret[0].(config.ActiveAgent)
	ret1, _ := ret[1].(agent.Model)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ActiveAgent indicates an expected call of ActiveAgent.
func (mr *MockCoordinatorMockRecorder) ActiveAgent(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveAgent", reflect.TypeOf((*MockCoordinator)(nil).ActiveAgent), ctx, sessionID)
}

// BeginAccepted mocks base method.
func (m *MockCoordinator) BeginAccepted(ctx context.Context, sessionID string) *agent.AcceptedRun {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginAccepted", ctx, sessionID)
	ret0, _ := ret[0].(*agent.AcceptedRun)
	return ret0
}

// BeginAccepted indicates an expected call of BeginAccepted.
func (mr *MockCoordinatorMockRecorder) BeginAccepted(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginAccepted", reflect.TypeOf((*MockCoordinator)(nil).BeginAccepted), ctx, sessionID)
}

// Cancel mocks base method.
func (m *MockCoordinator) Cancel(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel", sessionID)
}

// Cancel indicates an expected call of Cancel.
func (mr *MockCoordinatorMockRecorder) Cancel(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockCoordinator)(nil).Cancel), sessionID)
}

// CancelAll mocks base method.
func (m *MockCoordinator) CancelAll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelAll")
}

// CancelAll indicates an expected call of CancelAll.
func (mr *MockCoordinatorMockRecorder) CancelAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAll", reflect.TypeOf((*MockCoordinator)(nil).CancelAll))
}

// ClearQueue mocks base method.
func (m *MockCoordinator) ClearQueue(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearQueue", sessionID)
}

// ClearQueue indicates an expected call of ClearQueue.
func (mr *MockCoordinatorMockRecorder) ClearQueue(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearQueue", reflect.TypeOf((*MockCoordinator)(nil).ClearQueue), sessionID)
}

// DefaultModel mocks base method.
func (m *MockCoordinator) DefaultModel() agent.Model {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultModel")
	ret0, _ := ret[0].(agent.Model)
	return ret0
}

// DefaultModel indicates an expected call of DefaultModel.
func (mr *MockCoordinatorMockRecorder) DefaultModel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultModel", reflect.TypeOf((*MockCoordinator)(nil).DefaultModel))
}

// EditActiveAgent mocks base method.
func (m *MockCoordinator) EditActiveAgent(ctx context.Context, sessionID string, edit config.ActiveAgentEdit) (config.ActiveAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditActiveAgent", ctx, sessionID, edit)
	ret0, _ := ret[0].(config.ActiveAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditActiveAgent indicates an expected call of EditActiveAgent.
func (mr *MockCoordinatorMockRecorder) EditActiveAgent(ctx, sessionID, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditActiveAgent", reflect.TypeOf((*MockCoordinator)(nil).EditActiveAgent), ctx, sessionID, edit)
}

// GenerateAgent mocks base method.
func (m *MockCoordinator) GenerateAgent(ctx context.Context, description string) (config.Agent, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAgent", ctx, description)
	ret0, _ := ret[0].(config.Agent)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAgent indicates an expected call of GenerateAgent.
func (mr *MockCoordinatorMockRecorder) GenerateAgent(ctx, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAgent", reflect.TypeOf((*MockCoordinator)(nil).GenerateAgent), ctx, description)
}

// GenerateTitle mocks base method.
func (m *MockCoordinator) GenerateTitle(ctx context.Context, sessionID, prompt string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GenerateTitle", ctx, sessionID, prompt)
}

// GenerateTitle indicates an expected call of GenerateTitle.
func (mr *MockCoordinatorMockRecorder) GenerateTitle(ctx, sessionID, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTitle", reflect.TypeOf((*MockCoordinator)(nil).GenerateTitle), ctx, sessionID, prompt)
}

// IsBusy mocks base method.
func (m *MockCoordinator) IsBusy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBusy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBusy indicates an expected call of IsBusy.
func (mr *MockCoordinatorMockRecorder) IsBusy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBusy", reflect.TypeOf((*MockCoordinator)(nil).IsBusy))
}

// IsSessionBranch mocks base method.
func (m *MockCoordinator) IsSessionBranch(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSessionBranch", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSessionBranch indicates an expected call of IsSessionBranch.
func (mr *MockCoordinatorMockRecorder) IsSessionBranch(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSessionBranch", reflect.TypeOf((*MockCoordinator)(nil).IsSessionBranch), sessionID)
}

// IsSessionBusy mocks base method.
func (m *MockCoordinator) IsSessionBusy(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSessionBusy", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSessionBusy indicates an expected call of IsSessionBusy.
func (mr *MockCoordinatorMockRecorder) IsSessionBusy(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSessionBusy", reflect.TypeOf((*MockCoordinator)(nil).IsSessionBusy), sessionID)
}

// LockSession mocks base method.
func (m *MockCoordinator) LockSession(ctx context.Context, sessionID string) (func(), bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSession", ctx, sessionID)
	ret0, _ := ret[0].(func())
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// LockSession indicates an expected call of LockSession.
func (mr *MockCoordinatorMockRecorder) LockSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSession", reflect.TypeOf((*MockCoordinator)(nil).LockSession), ctx, sessionID)
}

// QueuedPrompts mocks base method.
func (m *MockCoordinator) QueuedPrompts(sessionID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueuedPrompts", sessionID)
	ret0, _ := ret[0].(int)
	return ret0
}

// QueuedPrompts indicates an expected call of QueuedPrompts.
func (mr *MockCoordinatorMockRecorder) QueuedPrompts(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueuedPrompts", reflect.TypeOf((*MockCoordinator)(nil).QueuedPrompts), sessionID)
}

// QueuedPromptsList mocks base method.
func (m *MockCoordinator) QueuedPromptsList(sessionID string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueuedPromptsList", sessionID)
	ret0, _ := ret[0].([]string)
	return ret0
}

// QueuedPromptsList indicates an expected call of QueuedPromptsList.
func (mr *MockCoordinatorMockRecorder) QueuedPromptsList(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueuedPromptsList", reflect.TypeOf((*MockCoordinator)(nil).QueuedPromptsList), sessionID)
}

// Run mocks base method.
func (m *MockCoordinator) Run(ctx context.Context, sessionID, prompt string, attachments ...message.Attachment) (*fantasy.AgentResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sessionID, prompt}
	for _, a := range attachments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].(*fantasy.AgentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockCoordinatorMockRecorder) Run(ctx, sessionID, prompt any, attachments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sessionID, prompt}, attachments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCoordinator)(nil).Run), varargs...)
}

// RunAccepted mocks base method.
func (m *MockCoordinator) RunAccepted(ctx context.Context, accept *agent.AcceptedRun, sessionID, prompt string, attachments ...message.Attachment) (*fantasy.AgentResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, accept, sessionID, prompt}
	for _, a := range attachments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunAccepted", varargs...)
	ret0, _ := ret[0].(*fantasy.AgentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAccepted indicates an expected call of RunAccepted.
func (mr *MockCoordinatorMockRecorder) RunAccepted(ctx, accept, sessionID, prompt any, attachments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, accept, sessionID, prompt}, attachments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAccepted", reflect.TypeOf((*MockCoordinator)(nil).RunAccepted), varargs...)
}

// Summarize mocks base method.
func (m *MockCoordinator) Summarize(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Summarize indicates an expected call of Summarize.
func (mr *MockCoordinatorMockRecorder) Summarize(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockCoordinator)(nil).Summarize), arg0, arg1)
}

// SwitchAgent mocks base method.
func (m *MockCoordinator) SwitchAgent(ctx context.Context, sessionID, agentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchAgent", ctx, sessionID, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchAgent indicates an expected call of SwitchAgent.
func (mr *MockCoordinatorMockRecorder) SwitchAgent(ctx, sessionID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchAgent", reflect.TypeOf((*MockCoordinator)(nil).SwitchAgent), ctx, sessionID, agentID)
}

// SwitchVariant mocks base method.
func (m *MockCoordinator) SwitchVariant(ctx context.Context, sessionID, variant string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchVariant", ctx, sessionID, variant)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchVariant indicates an expected call of SwitchVariant.
func (mr *MockCoordinatorMockRecorder) SwitchVariant(ctx, sessionID, variant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchVariant", reflect.TypeOf((*MockCoordinator)(nil).SwitchVariant), ctx, sessionID, variant)
}

// UpdateModels mocks base method.
func (m *MockCoordinator) UpdateModels(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModels", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateModels indicates an expected call of UpdateModels.
func (mr *MockCoordinatorMockRecorder) UpdateModels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModels", reflect.TypeOf((*MockCoordinator)(nil).UpdateModels), ctx)
}
