// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/session (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/cmd/mock_sessionservice_test.go -package=cmd -mock_names=Service=MockSessionService github.com/NaturalSelect/angela/internal/session Service
//

// Package cmd is a generated GoMock package.
package cmd

import (
	context "context"
	reflect "reflect"

	config "github.com/NaturalSelect/angela/internal/config"
	pubsub "github.com/NaturalSelect/angela/internal/pubsub"
	session "github.com/NaturalSelect/angela/internal/session"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionService is a mock of Service interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// AddCost mocks base method.
func (m *MockSessionService) AddCost(ctx context.Context, sessionID string, delta float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCost", ctx, sessionID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCost indicates an expected call of AddCost.
func (mr *MockSessionServiceMockRecorder) AddCost(ctx, sessionID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCost", reflect.TypeOf((*MockSessionService)(nil).AddCost), ctx, sessionID, delta)
}

// Create mocks base method.
func (m *MockSessionService) Create(ctx context.Context, title string) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, title)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionServiceMockRecorder) Create(ctx, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionService)(nil).Create), ctx, title)
}

// CreateAgentToolSessionID mocks base method.
func (m *MockSessionService) CreateAgentToolSessionID(messageID, toolCallID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgentToolSessionID", messageID, toolCallID)
	ret0, _ := ret[0].(string)
	return ret0
}

// CreateAgentToolSessionID indicates an expected call of CreateAgentToolSessionID.
func (mr *MockSessionServiceMockRecorder) CreateAgentToolSessionID(messageID, toolCallID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgentToolSessionID", reflect.TypeOf((*MockSessionService)(nil).CreateAgentToolSessionID), messageID, toolCallID)
}

// CreateTaskSession mocks base method.
func (m *MockSessionService) CreateTaskSession(ctx context.Context, toolCallID, parentSessionID, title string) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskSession", ctx, toolCallID, parentSessionID, title)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaskSession indicates an expected call of CreateTaskSession.
func (mr *MockSessionServiceMockRecorder) CreateTaskSession(ctx, toolCallID, parentSessionID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskSession", reflect.TypeOf((*MockSessionService)(nil).CreateTaskSession), ctx, toolCallID, parentSessionID, title)
}

// Delete mocks base method.
func (m *MockSessionService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockSessionService) Get(ctx context.Context, id string) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionService)(nil).Get), ctx, id)
}

// GetLast mocks base method.
func (m *MockSessionService) GetLast(ctx context.Context) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast", ctx)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLast indicates an expected call of GetLast.
func (mr *MockSessionServiceMockRecorder) GetLast(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast", reflect.TypeOf((*MockSessionService)(nil).GetLast), ctx)
}

// IsAgentToolSession mocks base method.
func (m *MockSessionService) IsAgentToolSession(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAgentToolSession", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAgentToolSession indicates an expected call of IsAgentToolSession.
func (mr *MockSessionServiceMockRecorder) IsAgentToolSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAgentToolSession", reflect.TypeOf((*MockSessionService)(nil).IsAgentToolSession), sessionID)
}

// List mocks base method.
func (m *MockSessionService) List(ctx context.Context) ([]session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSessionServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSessionService)(nil).List), ctx)
}

// ParseAgentToolSessionID mocks base method.
func (m *MockSessionService) ParseAgentToolSessionID(sessionID string) (string, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAgentToolSessionID", sessionID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// ParseAgentToolSessionID indicates an expected call of ParseAgentToolSessionID.
func (mr *MockSessionServiceMockRecorder) ParseAgentToolSessionID(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAgentToolSessionID", reflect.TypeOf((*MockSessionService)(nil).ParseAgentToolSessionID), sessionID)
}

// Rename mocks base method.
func (m *MockSessionService) Rename(ctx context.Context, id, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, id, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockSessionServiceMockRecorder) Rename(ctx, id, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockSessionService)(nil).Rename), ctx, id, title)
}

// Save mocks base method.
func (m *MockSessionService) Save(ctx context.Context, arg1 session.Session) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockSessionServiceMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionService)(nil).Save), ctx, arg1)
}

// Subscribe mocks base method.
func (m *MockSessionService) Subscribe(arg0 context.Context) <-chan pubsub.Event[session.Session] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0)
	ret0, _ := ret[0].(<-chan pubsub.Event[session.Session])
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSessionServiceMockRecorder) Subscribe(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSessionService)(nil).Subscribe), arg0)
}

// UpdateActiveAgent mocks base method.
func (m *MockSessionService) UpdateActiveAgent(ctx context.Context, id string, state config.ActiveAgentState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActiveAgent", ctx, id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActiveAgent indicates an expected call of UpdateActiveAgent.
func (mr *MockSessionServiceMockRecorder) UpdateActiveAgent(ctx, id, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActiveAgent", reflect.TypeOf((*MockSessionService)(nil).UpdateActiveAgent), ctx, id, state)
}

// UpdateTitleAndUsage mocks base method.
func (m *MockSessionService) UpdateTitleAndUsage(ctx context.Context, sessionID, title string, promptTokens, completionTokens int64, cost float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTitleAndUsage", ctx, sessionID, title, promptTokens, completionTokens, cost)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTitleAndUsage indicates an expected call of UpdateTitleAndUsage.
func (mr *MockSessionServiceMockRecorder) UpdateTitleAndUsage(ctx, sessionID, title, promptTokens, completionTokens, cost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTitleAndUsage", reflect.TypeOf((*MockSessionService)(nil).UpdateTitleAndUsage), ctx, sessionID, title, promptTokens, completionTokens, cost)
}
