// Code generated by MockGen. DO NOT EDIT.
// Source: internal/herdr/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/herdr/client.go -destination=internal/herdr/mock_sender_test.go -package=herdr -mock_names=sender=MockSender -exclude_interfaces=Event
//

// Package herdr is a generated GoMock package.
package herdr

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// close mocks base method.
func (m *MockSender) close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "close")
}

// close indicates an expected call of close.
func (mr *MockSenderMockRecorder) close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "close", reflect.TypeOf((*MockSender)(nil).close))
}

// send mocks base method.
func (m *MockSender) send(req reportRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "send", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// send indicates an expected call of send.
func (mr *MockSenderMockRecorder) send(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "send", reflect.TypeOf((*MockSender)(nil).send), req)
}
