// Code generated by MockGen. DO NOT EDIT.
// Source: charm.land/fantasy (interfaces: AgentTool)
//
// Generated by this command:
//
//	mockgen -destination=internal/agent/mock_agenttool_test.go -package=agent charm.land/fantasy AgentTool
//

// Package agent is a generated GoMock package.
package agent

import (
	context "context"
	reflect "reflect"

	fantasy "charm.land/fantasy"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentTool is a mock of AgentTool interface.
type MockAgentTool struct {
	ctrl     *gomock.Controller
	recorder *MockAgentToolMockRecorder
	isgomock struct{}
}

// MockAgentToolMockRecorder is the mock recorder for MockAgentTool.
type MockAgentToolMockRecorder struct {
	mock *MockAgentTool
}

// NewMockAgentTool creates a new mock instance.
func NewMockAgentTool(ctrl *gomock.Controller) *MockAgentTool {
	mock := &MockAgentTool{ctrl: ctrl}
	mock.recorder = &MockAgentToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentTool) EXPECT() *MockAgentToolMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockAgentTool) Info() fantasy.ToolInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info")
	ret0, _ := ret[0].(fantasy.ToolInfo)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockAgentToolMockRecorder) Info() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockAgentTool)(nil).Info))
}

// ProviderOptions mocks base method.
func (m *MockAgentTool) ProviderOptions() fantasy.ProviderOptions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProviderOptions")
	ret0, _ := ret[0].(fantasy.ProviderOptions)
	return ret0
}

// ProviderOptions indicates an expected call of ProviderOptions.
func (mr *MockAgentToolMockRecorder) ProviderOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProviderOptions", reflect.TypeOf((*MockAgentTool)(nil).ProviderOptions))
}

// Run mocks base method.
func (m *MockAgentTool) Run(ctx context.Context, params fantasy.ToolCall) (fantasy.ToolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, params)
	ret0, _ := ret[0].(fantasy.ToolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockAgentToolMockRecorder) Run(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAgentTool)(nil).Run), ctx, params)
}

// SetProviderOptions mocks base method.
func (m *MockAgentTool) SetProviderOptions(opts fantasy.ProviderOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProviderOptions", opts)
}

// SetProviderOptions indicates an expected call of SetProviderOptions.
func (mr *MockAgentToolMockRecorder) SetProviderOptions(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderOptions", reflect.TypeOf((*MockAgentTool)(nil).SetProviderOptions), opts)
}
