// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/agent (interfaces: SessionAgent)
//
// Generated by this command:
//
//	mockgen -destination=internal/agent/mock_sessionagent_test.go -package=agent github.com/NaturalSelect/angela/internal/agent SessionAgent
//

// Package agent is a generated GoMock package.
package agent

import (
	context "context"
	reflect "reflect"

	fantasy "charm.land/fantasy"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionAgent is a mock of SessionAgent interface.
type MockSessionAgent struct {
	ctrl     *gomock.Controller
	recorder *MockSessionAgentMockRecorder
	isgomock struct{}
}

// MockSessionAgentMockRecorder is the mock recorder for MockSessionAgent.
type MockSessionAgentMockRecorder struct {
	mock *MockSessionAgent
}

// NewMockSessionAgent creates a new mock instance.
func NewMockSessionAgent(ctrl *gomock.Controller) *MockSessionAgent {
	mock := &MockSessionAgent{ctrl: ctrl}
	mock.recorder = &MockSessionAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionAgent) EXPECT() *MockSessionAgentMockRecorder {
	return m.recorder
}

// AgentID mocks base method.
func (m *MockSessionAgent) AgentID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentID")
	ret0, _ := ret[0].(string)
	return ret0
}

// AgentID indicates an expected call of AgentID.
func (mr *MockSessionAgentMockRecorder) AgentID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentID", reflect.TypeOf((*MockSessionAgent)(nil).AgentID))
}

// BeginAccepted mocks base method.
func (m *MockSessionAgent) BeginAccepted(sessionID string) *AcceptedRun {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginAccepted", sessionID)
	ret0, _ := ret[0].(*AcceptedRun)
	return ret0
}

// BeginAccepted indicates an expected call of BeginAccepted.
func (mr *MockSessionAgentMockRecorder) BeginAccepted(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginAccepted", reflect.TypeOf((*MockSessionAgent)(nil).BeginAccepted), sessionID)
}

// Cancel mocks base method.
func (m *MockSessionAgent) Cancel(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel", sessionID)
}

// Cancel indicates an expected call of Cancel.
func (mr *MockSessionAgentMockRecorder) Cancel(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockSessionAgent)(nil).Cancel), sessionID)
}

// CancelAll mocks base method.
func (m *MockSessionAgent) CancelAll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelAll")
}

// CancelAll indicates an expected call of CancelAll.
func (mr *MockSessionAgentMockRecorder) CancelAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAll", reflect.TypeOf((*MockSessionAgent)(nil).CancelAll))
}

// ClearQueue mocks base method.
func (m *MockSessionAgent) ClearQueue(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearQueue", sessionID)
}

// ClearQueue indicates an expected call of ClearQueue.
func (mr *MockSessionAgentMockRecorder) ClearQueue(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearQueue", reflect.TypeOf((*MockSessionAgent)(nil).ClearQueue), sessionID)
}

// IsBusy mocks base method.
func (m *MockSessionAgent) IsBusy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBusy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBusy indicates an expected call of IsBusy.
func (mr *MockSessionAgentMockRecorder) IsBusy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBusy", reflect.TypeOf((*MockSessionAgent)(nil).IsBusy))
}

// IsSessionBusy mocks base method.
func (m *MockSessionAgent) IsSessionBusy(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSessionBusy", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSessionBusy indicates an expected call of IsSessionBusy.
func (mr *MockSessionAgentMockRecorder) IsSessionBusy(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSessionBusy", reflect.TypeOf((*MockSessionAgent)(nil).IsSessionBusy), sessionID)
}

// LockSession mocks base method.
func (m *MockSessionAgent) LockSession(sessionID string) func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockSession", sessionID)
	ret0, _ := ret[0].(func())
	return ret0
}

// LockSession indicates an expected call of LockSession.
func (mr *MockSessionAgentMockRecorder) LockSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockSession", reflect.TypeOf((*MockSessionAgent)(nil).LockSession), sessionID)
}

// QueuedPrompts mocks base method.
func (m *MockSessionAgent) QueuedPrompts(sessionID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueuedPrompts", sessionID)
	ret0, _ := ret[0].(int)
	return ret0
}

// QueuedPrompts indicates an expected call of QueuedPrompts.
func (mr *MockSessionAgentMockRecorder) QueuedPrompts(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueuedPrompts", reflect.TypeOf((*MockSessionAgent)(nil).QueuedPrompts), sessionID)
}

// QueuedPromptsList mocks base method.
func (m *MockSessionAgent) QueuedPromptsList(sessionID string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueuedPromptsList", sessionID)
	ret0, _ := ret[0].([]string)
	return ret0
}

// QueuedPromptsList indicates an expected call of QueuedPromptsList.
func (mr *MockSessionAgentMockRecorder) QueuedPromptsList(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueuedPromptsList", reflect.TypeOf((*MockSessionAgent)(nil).QueuedPromptsList), sessionID)
}

// Run mocks base method.
func (m *MockSessionAgent) Run(arg0 context.Context, arg1 SessionAgentCall) (*fantasy.AgentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(*fantasy.AgentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockSessionAgentMockRecorder) Run(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSessionAgent)(nil).Run), arg0, arg1)
}

// Summarize mocks base method.
func (m *MockSessionAgent) Summarize(arg0 context.Context, arg1 string, arg2 resolvedAgent, arg3 fantasy.ProviderOptions, arg4 func(context.Context, *fantasy.ProviderError) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Summarize indicates an expected call of Summarize.
func (mr *MockSessionAgentMockRecorder) Summarize(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockSessionAgent)(nil).Summarize), arg0, arg1, arg2, arg3, arg4)
}
