// Package images provides storage and retrieval of images generated by
// LLM image tools (e.g. ImageGenerate/ImageEdit), persisted in SQLite
// alongside the metadata describing how each image was produced.
package images

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/NaturalSelect/angela/internal/db"
	"github.com/google/uuid"
)

// ErrNotFound is returned when a requested generated image does not
// exist.
var ErrNotFound = errors.New("image not found")

// Image represents a generated image stored in the database, together
// with the metadata describing how it was produced.
type Image struct {
	ID             string
	SessionID      string
	ToolCallID     string
	Prompt         string
	RevisedPrompt  string
	SourceImageIDs []string
	Provider       string
	Model          string
	MIMEType       string
	Width          int
	Height         int
	Data           []byte
	CreatedAt      int64
}

// CreateParams holds the fields required to persist a newly generated
// image. ID and CreatedAt are assigned by the service.
type CreateParams struct {
	SessionID      string
	ToolCallID     string
	Prompt         string
	RevisedPrompt  string
	SourceImageIDs []string
	Provider       string
	Model          string
	MIMEType       string
	Width          int
	Height         int
	Data           []byte
}

// Service stores and retrieves generated images.
type Service interface {
	// Create persists a newly generated image and returns the stored
	// record, including its generated ID and creation timestamp.
	Create(ctx context.Context, p CreateParams) (Image, error)

	// Get retrieves a generated image by its ID. It returns
	// ErrNotFound if no image with that ID exists.
	Get(ctx context.Context, id string) (Image, error)

	// ListBySession retrieves the metadata for every image generated
	// in a session, newest first. The returned images have no Data,
	// so this is cheap to call even for sessions with many images.
	ListBySession(ctx context.Context, sessionID string) ([]Image, error)
}

type service struct {
	q *db.Queries
}

// NewService creates a new generated image service.
func NewService(q *db.Queries) Service {
	return &service{q: q}
}

// Create persists a newly generated image.
func (s *service) Create(ctx context.Context, p CreateParams) (Image, error) {
	sourceImageIDs, err := marshalSourceImageIDs(p.SourceImageIDs)
	if err != nil {
		return Image{}, err
	}

	row, err := s.q.CreateGeneratedImage(ctx, db.CreateGeneratedImageParams{
		ID:             newImageID(),
		SessionID:      p.SessionID,
		ToolCallID:     p.ToolCallID,
		Prompt:         p.Prompt,
		RevisedPrompt:  p.RevisedPrompt,
		SourceImageIds: sourceImageIDs,
		Provider:       p.Provider,
		Model:          p.Model,
		MimeType:       p.MIMEType,
		Width:          int64(p.Width),
		Height:         int64(p.Height),
		Data:           p.Data,
	})
	if err != nil {
		return Image{}, fmt.Errorf("creating generated image: %w", err)
	}

	return rowToImage(row)
}

// Get retrieves a generated image by its ID.
func (s *service) Get(ctx context.Context, id string) (Image, error) {
	row, err := s.q.GetGeneratedImage(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Image{}, ErrNotFound
		}
		return Image{}, fmt.Errorf("getting generated image: %w", err)
	}

	return rowToImage(row)
}

// ListBySession retrieves the metadata for every image generated in a
// session, newest first.
func (s *service) ListBySession(ctx context.Context, sessionID string) ([]Image, error) {
	rows, err := s.q.ListGeneratedImagesBySession(ctx, sessionID)
	if err != nil {
		return nil, fmt.Errorf("listing generated images: %w", err)
	}

	imgs := make([]Image, len(rows))
	for i, row := range rows {
		img, err := listRowToImage(row)
		if err != nil {
			return nil, err
		}
		imgs[i] = img
	}
	return imgs, nil
}

// marshalSourceImageIDs encodes the source image IDs as a JSON array
// for storage. A nil slice is stored as an empty array rather than
// JSON null so the column always round-trips to a valid []string.
func marshalSourceImageIDs(ids []string) (string, error) {
	if ids == nil {
		ids = []string{}
	}
	raw, err := json.Marshal(ids)
	if err != nil {
		return "", fmt.Errorf("marshaling source image ids: %w", err)
	}
	return string(raw), nil
}

// rowToImage converts a generated database row into the public Image
// type, decoding the JSON-encoded source image IDs column.
func rowToImage(row db.GeneratedImage) (Image, error) {
	sourceImageIDs, err := unmarshalSourceImageIDs(row.SourceImageIds)
	if err != nil {
		return Image{}, err
	}

	return Image{
		ID:             row.ID,
		SessionID:      row.SessionID,
		ToolCallID:     row.ToolCallID,
		Prompt:         row.Prompt,
		RevisedPrompt:  row.RevisedPrompt,
		SourceImageIDs: sourceImageIDs,
		Provider:       row.Provider,
		Model:          row.Model,
		MIMEType:       row.MimeType,
		Width:          int(row.Width),
		Height:         int(row.Height),
		Data:           row.Data,
		CreatedAt:      row.CreatedAt,
	}, nil
}

// listRowToImage converts a ListGeneratedImagesBySession row into the
// public Image type. The row carries no Data column, so the returned
// Image's Data is always nil.
func listRowToImage(row db.ListGeneratedImagesBySessionRow) (Image, error) {
	sourceImageIDs, err := unmarshalSourceImageIDs(row.SourceImageIds)
	if err != nil {
		return Image{}, err
	}

	return Image{
		ID:             row.ID,
		SessionID:      row.SessionID,
		ToolCallID:     row.ToolCallID,
		Prompt:         row.Prompt,
		RevisedPrompt:  row.RevisedPrompt,
		SourceImageIDs: sourceImageIDs,
		Provider:       row.Provider,
		Model:          row.Model,
		MIMEType:       row.MimeType,
		Width:          int(row.Width),
		Height:         int(row.Height),
		CreatedAt:      row.CreatedAt,
	}, nil
}

// unmarshalSourceImageIDs decodes the JSON-encoded source image IDs
// column shared by both the single-row and list queries.
func unmarshalSourceImageIDs(raw string) ([]string, error) {
	var sourceImageIDs []string
	if err := json.Unmarshal([]byte(raw), &sourceImageIDs); err != nil {
		return nil, fmt.Errorf("unmarshaling source image ids: %w", err)
	}
	return sourceImageIDs, nil
}

// newImageID generates a new unique identifier for a generated image,
// e.g. "img_1a2b3c4d5e6f".
func newImageID() string {
	hex := strings.ReplaceAll(uuid.New().String(), "-", "")
	return "img_" + hex[:12]
}
