// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/posthog/posthog-go (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=internal/event/mock_client_test.go -package=event -mock_names=Client=MockPosthogClient github.com/posthog/posthog-go Client
//

// Package event is a generated GoMock package.
package event

import (
	context "context"
	reflect "reflect"

	posthog "github.com/posthog/posthog-go"
	gomock "go.uber.org/mock/gomock"
)

// MockPosthogClient is a mock of Client interface.
type MockPosthogClient struct {
	ctrl     *gomock.Controller
	recorder *MockPosthogClientMockRecorder
	isgomock struct{}
}

// MockPosthogClientMockRecorder is the mock recorder for MockPosthogClient.
type MockPosthogClientMockRecorder struct {
	mock *MockPosthogClient
}

// NewMockPosthogClient creates a new mock instance.
func NewMockPosthogClient(ctrl *gomock.Controller) *MockPosthogClient {
	mock := &MockPosthogClient{ctrl: ctrl}
	mock.recorder = &MockPosthogClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPosthogClient) EXPECT() *MockPosthogClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPosthogClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPosthogClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPosthogClient)(nil).Close))
}

// CloseWithContext mocks base method.
func (m *MockPosthogClient) CloseWithContext(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseWithContext", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseWithContext indicates an expected call of CloseWithContext.
func (mr *MockPosthogClientMockRecorder) CloseWithContext(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseWithContext", reflect.TypeOf((*MockPosthogClient)(nil).CloseWithContext), arg0)
}

// Enqueue mocks base method.
func (m *MockPosthogClient) Enqueue(arg0 posthog.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockPosthogClientMockRecorder) Enqueue(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockPosthogClient)(nil).Enqueue), arg0)
}

// EvaluateFlags mocks base method.
func (m *MockPosthogClient) EvaluateFlags(arg0 posthog.EvaluateFlagsPayload) (*posthog.FeatureFlagEvaluations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateFlags", arg0)
	ret0, _ := ret[0].(*posthog.FeatureFlagEvaluations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateFlags indicates an expected call of EvaluateFlags.
func (mr *MockPosthogClientMockRecorder) EvaluateFlags(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateFlags", reflect.TypeOf((*MockPosthogClient)(nil).EvaluateFlags), arg0)
}

// GetAllFlags mocks base method.
func (m *MockPosthogClient) GetAllFlags(arg0 posthog.FeatureFlagPayloadNoKey) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFlags", arg0)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFlags indicates an expected call of GetAllFlags.
func (mr *MockPosthogClientMockRecorder) GetAllFlags(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFlags", reflect.TypeOf((*MockPosthogClient)(nil).GetAllFlags), arg0)
}

// GetFeatureFlag mocks base method.
func (m *MockPosthogClient) GetFeatureFlag(arg0 posthog.FeatureFlagPayload) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureFlag", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatureFlag indicates an expected call of GetFeatureFlag.
func (mr *MockPosthogClientMockRecorder) GetFeatureFlag(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureFlag", reflect.TypeOf((*MockPosthogClient)(nil).GetFeatureFlag), arg0)
}

// GetFeatureFlagPayload mocks base method.
func (m *MockPosthogClient) GetFeatureFlagPayload(arg0 posthog.FeatureFlagPayload) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureFlagPayload", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatureFlagPayload indicates an expected call of GetFeatureFlagPayload.
func (mr *MockPosthogClientMockRecorder) GetFeatureFlagPayload(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureFlagPayload", reflect.TypeOf((*MockPosthogClient)(nil).GetFeatureFlagPayload), arg0)
}

// GetFeatureFlagResult mocks base method.
func (m *MockPosthogClient) GetFeatureFlagResult(arg0 posthog.FeatureFlagPayload) (*posthog.FeatureFlagResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureFlagResult", arg0)
	ret0, _ := ret[0].(*posthog.FeatureFlagResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatureFlagResult indicates an expected call of GetFeatureFlagResult.
func (mr *MockPosthogClientMockRecorder) GetFeatureFlagResult(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureFlagResult", reflect.TypeOf((*MockPosthogClient)(nil).GetFeatureFlagResult), arg0)
}

// GetRemoteConfigPayload mocks base method.
func (m *MockPosthogClient) GetRemoteConfigPayload(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteConfigPayload", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteConfigPayload indicates an expected call of GetRemoteConfigPayload.
func (mr *MockPosthogClientMockRecorder) GetRemoteConfigPayload(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteConfigPayload", reflect.TypeOf((*MockPosthogClient)(nil).GetRemoteConfigPayload), arg0)
}

// IsFeatureEnabled mocks base method.
func (m *MockPosthogClient) IsFeatureEnabled(arg0 posthog.FeatureFlagPayload) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFeatureEnabled", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFeatureEnabled indicates an expected call of IsFeatureEnabled.
func (mr *MockPosthogClientMockRecorder) IsFeatureEnabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFeatureEnabled", reflect.TypeOf((*MockPosthogClient)(nil).IsFeatureEnabled), arg0)
}

// ReloadFeatureFlags mocks base method.
func (m *MockPosthogClient) ReloadFeatureFlags() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadFeatureFlags")
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadFeatureFlags indicates an expected call of ReloadFeatureFlags.
func (mr *MockPosthogClientMockRecorder) ReloadFeatureFlags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadFeatureFlags", reflect.TypeOf((*MockPosthogClient)(nil).ReloadFeatureFlags))
}
