// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/catwalk.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/catwalk.go -destination=internal/config/mock_catwalkclient_test.go -package=config -mock_names=catwalkClient=MockCatwalkClient
//

// Package config is a generated GoMock package.
package config

import (
	context "context"
	reflect "reflect"

	catwalk "charm.land/catwalk/pkg/catwalk"
	gomock "go.uber.org/mock/gomock"
)

// MockCatwalkClient is a mock of catwalkClient interface.
type MockCatwalkClient struct {
	ctrl     *gomock.Controller
	recorder *MockCatwalkClientMockRecorder
	isgomock struct{}
}

// MockCatwalkClientMockRecorder is the mock recorder for MockCatwalkClient.
type MockCatwalkClientMockRecorder struct {
	mock *MockCatwalkClient
}

// NewMockCatwalkClient creates a new mock instance.
func NewMockCatwalkClient(ctrl *gomock.Controller) *MockCatwalkClient {
	mock := &MockCatwalkClient{ctrl: ctrl}
	mock.recorder = &MockCatwalkClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatwalkClient) EXPECT() *MockCatwalkClientMockRecorder {
	return m.recorder
}

// GetProviders mocks base method.
func (m *MockCatwalkClient) GetProviders(arg0 context.Context, arg1 string) ([]catwalk.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviders", arg0, arg1)
	ret0, _ := ret[0].([]catwalk.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviders indicates an expected call of GetProviders.
func (mr *MockCatwalkClientMockRecorder) GetProviders(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviders", reflect.TypeOf((*MockCatwalkClient)(nil).GetProviders), arg0, arg1)
}
