// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/config (interfaces: VariableResolver)
//
// Generated by this command:
//
//	mockgen -destination=internal/config/mock_variableresolver_test.go -package=config github.com/NaturalSelect/angela/internal/config VariableResolver
//

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVariableResolver is a mock of VariableResolver interface.
type MockVariableResolver struct {
	ctrl     *gomock.Controller
	recorder *MockVariableResolverMockRecorder
	isgomock struct{}
}

// MockVariableResolverMockRecorder is the mock recorder for MockVariableResolver.
type MockVariableResolverMockRecorder struct {
	mock *MockVariableResolver
}

// NewMockVariableResolver creates a new mock instance.
func NewMockVariableResolver(ctrl *gomock.Controller) *MockVariableResolver {
	mock := &MockVariableResolver{ctrl: ctrl}
	mock.recorder = &MockVariableResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVariableResolver) EXPECT() *MockVariableResolverMockRecorder {
	return m.recorder
}

// ResolveValue mocks base method.
func (m *MockVariableResolver) ResolveValue(value string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveValue", value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveValue indicates an expected call of ResolveValue.
func (mr *MockVariableResolverMockRecorder) ResolveValue(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveValue", reflect.TypeOf((*MockVariableResolver)(nil).ResolveValue), value)
}
