// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generated_images.sql

package db

import (
	"context"
)

const createGeneratedImage = `-- name: CreateGeneratedImage :one
INSERT INTO generated_images (
    id,
    session_id,
    tool_call_id,
    prompt,
    revised_prompt,
    source_image_ids,
    provider,
    model,
    mime_type,
    width,
    height,
    data,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now')
)
RETURNING id, session_id, tool_call_id, prompt, revised_prompt, source_image_ids, provider, model, mime_type, width, height, data, created_at
`

type CreateGeneratedImageParams struct {
	ID             string `json:"id"`
	SessionID      string `json:"session_id"`
	ToolCallID     string `json:"tool_call_id"`
	Prompt         string `json:"prompt"`
	RevisedPrompt  string `json:"revised_prompt"`
	SourceImageIds string `json:"source_image_ids"`
	Provider       string `json:"provider"`
	Model          string `json:"model"`
	MimeType       string `json:"mime_type"`
	Width          int64  `json:"width"`
	Height         int64  `json:"height"`
	Data           []byte `json:"data"`
}

func (q *Queries) CreateGeneratedImage(ctx context.Context, arg CreateGeneratedImageParams) (GeneratedImage, error) {
	row := q.queryRow(ctx, q.createGeneratedImageStmt, createGeneratedImage,
		arg.ID,
		arg.SessionID,
		arg.ToolCallID,
		arg.Prompt,
		arg.RevisedPrompt,
		arg.SourceImageIds,
		arg.Provider,
		arg.Model,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.Data,
	)
	var i GeneratedImage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ToolCallID,
		&i.Prompt,
		&i.RevisedPrompt,
		&i.SourceImageIds,
		&i.Provider,
		&i.Model,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getGeneratedImage = `-- name: GetGeneratedImage :one
SELECT id, session_id, tool_call_id, prompt, revised_prompt, source_image_ids, provider, model, mime_type, width, height, data, created_at
FROM generated_images
WHERE id = ? LIMIT 1
`

func (q *Queries) GetGeneratedImage(ctx context.Context, id string) (GeneratedImage, error) {
	row := q.queryRow(ctx, q.getGeneratedImageStmt, getGeneratedImage, id)
	var i GeneratedImage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ToolCallID,
		&i.Prompt,
		&i.RevisedPrompt,
		&i.SourceImageIds,
		&i.Provider,
		&i.Model,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}
