// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/question (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/agent/tools/mock_questionservice_test.go -package=tools -mock_names=Service=MockQuestionService github.com/NaturalSelect/angela/internal/question Service
//

// Package tools is a generated GoMock package.
package tools

import (
	context "context"
	reflect "reflect"

	pubsub "github.com/NaturalSelect/angela/internal/pubsub"
	question "github.com/NaturalSelect/angela/internal/question"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestionService is a mock of Service interface.
type MockQuestionService struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionServiceMockRecorder
	isgomock struct{}
}

// MockQuestionServiceMockRecorder is the mock recorder for MockQuestionService.
type MockQuestionServiceMockRecorder struct {
	mock *MockQuestionService
}

// NewMockQuestionService creates a new mock instance.
func NewMockQuestionService(ctrl *gomock.Controller) *MockQuestionService {
	mock := &MockQuestionService{ctrl: ctrl}
	mock.recorder = &MockQuestionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionService) EXPECT() *MockQuestionServiceMockRecorder {
	return m.recorder
}

// Answer mocks base method.
func (m *MockQuestionService) Answer(answers []question.Answer) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Answer", answers)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Answer indicates an expected call of Answer.
func (mr *MockQuestionServiceMockRecorder) Answer(answers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Answer", reflect.TypeOf((*MockQuestionService)(nil).Answer), answers)
}

// Ask mocks base method.
func (m *MockQuestionService) Ask(ctx context.Context, req question.Request) ([]question.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ask", ctx, req)
	ret0, _ := ret[0].([]question.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ask indicates an expected call of Ask.
func (mr *MockQuestionServiceMockRecorder) Ask(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ask", reflect.TypeOf((*MockQuestionService)(nil).Ask), ctx, req)
}

// Cancel mocks base method.
func (m *MockQuestionService) Cancel() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockQuestionServiceMockRecorder) Cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockQuestionService)(nil).Cancel))
}

// Subscribe mocks base method.
func (m *MockQuestionService) Subscribe(arg0 context.Context) <-chan pubsub.Event[question.Request] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0)
	ret0, _ := ret[0].(<-chan pubsub.Event[question.Request])
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockQuestionServiceMockRecorder) Subscribe(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockQuestionService)(nil).Subscribe), arg0)
}

// SubscribeNotifications mocks base method.
func (m *MockQuestionService) SubscribeNotifications(ctx context.Context) <-chan pubsub.Event[question.Notification] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeNotifications", ctx)
	ret0, _ := ret[0].(<-chan pubsub.Event[question.Notification])
	return ret0
}

// SubscribeNotifications indicates an expected call of SubscribeNotifications.
func (mr *MockQuestionServiceMockRecorder) SubscribeNotifications(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNotifications", reflect.TypeOf((*MockQuestionService)(nil).SubscribeNotifications), ctx)
}
