// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NaturalSelect/angela/internal/filetracker (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=internal/agent/tools/mock_filetracker_test.go -package=tools -mock_names=Service=MockFileTracker github.com/NaturalSelect/angela/internal/filetracker Service
//

// Package tools is a generated GoMock package.
package tools

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockFileTracker is a mock of Service interface.
type MockFileTracker struct {
	ctrl     *gomock.Controller
	recorder *MockFileTrackerMockRecorder
	isgomock struct{}
}

// MockFileTrackerMockRecorder is the mock recorder for MockFileTracker.
type MockFileTrackerMockRecorder struct {
	mock *MockFileTracker
}

// NewMockFileTracker creates a new mock instance.
func NewMockFileTracker(ctrl *gomock.Controller) *MockFileTracker {
	mock := &MockFileTracker{ctrl: ctrl}
	mock.recorder = &MockFileTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileTracker) EXPECT() *MockFileTrackerMockRecorder {
	return m.recorder
}

// LastReadTime mocks base method.
func (m *MockFileTracker) LastReadTime(ctx context.Context, sessionID, path string) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastReadTime", ctx, sessionID, path)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// LastReadTime indicates an expected call of LastReadTime.
func (mr *MockFileTrackerMockRecorder) LastReadTime(ctx, sessionID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastReadTime", reflect.TypeOf((*MockFileTracker)(nil).LastReadTime), ctx, sessionID, path)
}

// ListReadFiles mocks base method.
func (m *MockFileTracker) ListReadFiles(ctx context.Context, sessionID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReadFiles", ctx, sessionID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReadFiles indicates an expected call of ListReadFiles.
func (mr *MockFileTrackerMockRecorder) ListReadFiles(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReadFiles", reflect.TypeOf((*MockFileTracker)(nil).ListReadFiles), ctx, sessionID)
}

// RecordRead mocks base method.
func (m *MockFileTracker) RecordRead(ctx context.Context, sessionID, path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRead", ctx, sessionID, path)
}

// RecordRead indicates an expected call of RecordRead.
func (mr *MockFileTrackerMockRecorder) RecordRead(ctx, sessionID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRead", reflect.TypeOf((*MockFileTracker)(nil).RecordRead), ctx, sessionID, path)
}
