name: Update files

on:
  push:
    branches: [main]
    paths:
      - "internal/config/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - run: go run . schema > ./schema.json
      - name: Check for changes
        id: diff
        run: |
          git diff --quiet && echo "changed=false" >> "$GITHUB_OUTPUT" || echo "changed=true" >> "$GITHUB_OUTPUT"
      - name: Create Pull Request
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          branch: chore/auto-update-generated-files
          commit-message: "chore: auto-update generated files"
          title: "chore: auto-update generated files"
          body: "Automated update of `schema.json`."
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          labels: automated
